---
# This play sets up the main Satellite Server
# This must complete successfully before creating any capsule servers
# We use an activation key to ensure accuracy in our pools and repositories


- import_tasks: registration_and_repositories.yml

- import_tasks: install_idm_client.yml
  when: install_idm_client == true

- import_tasks: generate_certs.yml
  when: generate_certs == true and install_idm_client == true

- import_tasks: check_certs.yml
  when: generate_certs == true and install_idm_client == true

- import_tasks: foreman_prepare_realm.yml
  when: generate_certs == true and install_idm_client == true

- import_tasks: sat_firewalld_config.yml

- import_tasks: install_satellite.yml

- import_tasks: setup_hammer.yml
  when: setup_hammer == true

- import_tasks: upload_manifest.yml
  when: setup_hammer == true

- import_tasks: setup_virtwho.yml
  when: setup_virtwho == true

